### ISSUE TITLE
Error from COBRApyBasedFBA_server_test.py

### ISSUE THREAD

**Issue by braceal** [kbaseapps/COBRApyBasedFBA#3]
Error output

```
======================================================================
ERROR: Failure: KeyError ('getpwuid(): uid not found: 1000')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/miniconda/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/miniconda/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/miniconda/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/miniconda/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/miniconda/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/miniconda/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/kb/module/test/COBRApyBasedFBA_server_test.py", line 18, in <module>
    from COBRApyBasedFBA.COBRApyBasedFBAServer import MethodContext
  File "/kb/module/lib/COBRApyBasedFBA/COBRApyBasedFBAServer.py", line 490, in <module>
    application = Application()
  File "/kb/module/lib/COBRApyBasedFBA/COBRApyBasedFBAServer.py", line 334, in __init__
    config=get_config_file())
  File "/kb/deployment/lib/biokbase/log.py", line 137, in __init__
    self.user = _getpass.getuser()
  File "/miniconda/lib/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000'

```

@Fxe Let me know what you think of this

**Comment by braceal** [comment]
Resolved. Old kbase-sdk version.
